apiVersion: tekton.dev/v1beta1
kind: PipelineResource
metadata:
  name: git-repo
spec:
  type: git
  params:
    - name: url
      value: "https://github.com/Saravanan-5k/Devops-assesment.git"
    - name: revision
      value: "main"

